apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.userService.name | quote }}
  labels:
    {{- include "devpulse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.userService.service.type | quote }}
  ports:
    - port: {{ .Values.userService.service.port }}
      targetPort: {{ .Values.userService.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "devpulse.selectorLabels" . | nindent 4 }}
